package listadobleenlazada;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class principal extends javax.swing.JFrame {

    ListaDoble lista = new ListaDoble();
    int elemento;
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNaddFin = new javax.swing.JButton();
        BTNaddIncio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BTNremoveInicio = new javax.swing.JButton();
        BTNremoveFinal = new javax.swing.JButton();
        BTNremove = new javax.swing.JButton();
        TXTinsertar = new javax.swing.JTextField();
        TXTeliminar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTbuscar = new javax.swing.JTextField();
        TXTmodificar = new javax.swing.JTextField();
        BTNbuscar = new javax.swing.JButton();
        BTNmodificar = new javax.swing.JButton();
        BTNmostrarInicio = new javax.swing.JButton();
        BTNmostrarFin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("LISTA DOBLES ENLAZADAS");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("INSERTAR....");

        BTNaddFin.setText("INSERTAR AL FINAL");
        BTNaddFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaddFinActionPerformed(evt);
            }
        });

        BTNaddIncio.setText("INSERTAR AL INCIO");
        BTNaddIncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaddIncioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("ELIMINAR....");

        BTNremoveInicio.setText("ELIMINAR AL INCIO");
        BTNremoveInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNremoveInicioActionPerformed(evt);
            }
        });

        BTNremoveFinal.setText("ELIMINAR AL FINAL");
        BTNremoveFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNremoveFinalActionPerformed(evt);
            }
        });

        BTNremove.setText("ELIMINAR ");
        BTNremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNremoveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("BUSCAR...");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("MODIFICAR...");

        BTNbuscar.setText("BUSCAR");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        BTNmodificar.setText("MODIFICAR");
        BTNmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmodificarActionPerformed(evt);
            }
        });

        BTNmostrarInicio.setText("MOSTRAR INICIO/FIN");
        BTNmostrarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmostrarInicioActionPerformed(evt);
            }
        });

        BTNmostrarFin.setText("MOSTRAR FIN/INICIO");
        BTNmostrarFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmostrarFinActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(53, 53, 53)
                                        .addComponent(TXTinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNbuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTNmodificar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNremove)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTNremoveInicio)
                                    .addComponent(BTNaddIncio))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(BTNaddFin))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNremoveFinal))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(TXTeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(BTNmostrarInicio)
                        .addGap(32, 32, 32)
                        .addComponent(BTNmostrarFin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNaddFin)
                    .addComponent(BTNaddIncio))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNremove)
                    .addComponent(TXTeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNremoveFinal)
                    .addComponent(BTNremoveInicio))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNbuscar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNmodificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNmostrarInicio)
                    .addComponent(BTNmostrarFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>                        

    private void BTNaddIncioActionPerformed(java.awt.event.ActionEvent evt) {                                            

        if (TXTinsertar.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un Dato", "ERROR", JOptionPane.QUESTION_MESSAGE);
        } else {
            lista.addInicio(Integer.parseInt(TXTinsertar.getText()));
            TXTinsertar.setText("");
            JOptionPane.showMessageDialog(null, "Elemento insertado al inicio");
        }
    }                                           

    private void BTNaddFinActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (TXTinsertar.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese un Dato", "ERROR", JOptionPane.QUESTION_MESSAGE);
        } else {
            lista.addFinal(Integer.parseInt(TXTinsertar.getText()));
            TXTinsertar.setText("");
            JOptionPane.showMessageDialog(null, "Elemento insertado al final");
        }
    }                                         

    private void BTNremoveInicioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (!lista.estaVacia()) {
            elemento = lista.removeInicio();
            JOptionPane.showMessageDialog(null, "El elemento eliminado es: " + elemento, "Eliminando..",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                               

    private void BTNremoveFinalActionPerformed(java.awt.event.ActionEvent evt) {                                               

        if (!lista.estaVacia()) {
            elemento = lista.removeFinal();
            JOptionPane.showMessageDialog(null, "El elemento eliminado es: " + elemento, "Eliminando..",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                              

    private void BTNremoveActionPerformed(java.awt.event.ActionEvent evt) {                                          
        lista.removeValor(Integer.parseInt(TXTeliminar.getText()));
        JOptionPane.showMessageDialog(null, "El elemento se a eliminado. ", "Eliminando..",
                JOptionPane.INFORMATION_MESSAGE);
    }                                         

    private void BTNmostrarInicioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if (!lista.estaVacia()) {
            lista.mostrarInicioFin();
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                                

    private void BTNmostrarFinActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (!lista.estaVacia()) {
            lista.mostrarFinInicio();
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                             

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!lista.estaVacia()) {
            lista.buscarValor(Integer.parseInt(TXTbuscar.getText()));
            TXTbuscar.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                         

    private void BTNmodificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (!lista.estaVacia()) {
            lista.modificarValor(Integer.parseInt(TXTmodificar.getText()));
            TXTmodificar.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No hay Nodos aun..!!", "Lista Vacia",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        dispose();
    }